# Copyright 2020 sakaki (sakaki@deciban.com)
# Distributed under the terms of the GNU General Public License v2

EAPI=7

JAVA_PKG_IUSE=""

inherit java-pkg-2 java-maven-pkg git-r3

DESCRIPTION="JNI component for the usrsctp library"
SRC_URI=""
HOMEPAGE="https://github.com/mstyura/jitsi-sctp"
RESTRICT="mirror"

# no indiscriminate cleaning please (we have downloaded jars)
JAVA_PKG_NO_CLEAN=1

LICENSE="Apache-2.0"
SLOT="1"
KEYWORDS="~amd64 ~arm64"
IUSE=""

EGIT_REPO_URI="https://github.com/mstyura/jitsi-sctp.git"
# all submodules (default)
EGIT_BRANCH="master"
# following is tip commit at the ebuild release date
EGIT_COMMIT="f379da2db581aec326a0c4a06aaf4555b58b3f95"

# TODO: add more Portage-supplied deps, replacing Maven jars
# One - dom4j:1 - has been added to demonstrate the pattern

CP_DEPEND="
	dev-java/dom4j:1
"
CDEPEND="
"
DEPEND="
	${CP_DEPEND}
	${CDEPEND}
"
RDEPEND="
	${CP_DEPEND}
	${CDEPEND}
	>=virtual/jre-1.8
"
BDEPEND="
	${CP_DEPEND}
	${CDEPEND}
	>=virtual/jdk-1.8
"

# artefacts installed through Portage, comma or colon separated,
# which must be on the classpath at runtime
# see java-config -l for name format

JAVA_GENTOO_CLASSPATH="dom4j-1"

# additional fully qualified jar classpaths; colon separated

JAVA_GENTOO_CLASSPATH_EXTRA=""

# Even though some of EMAVEN_VENDOR will not be used at runtime, the full
# set is required in order to satisfy the Maven build system. A baseline
# ebuild (with EMAVEN_VENDOR automatically populated for you) can be created
# by using mvn2ebuild, in place of mvn, within a working project. Please see
# app-portage/mvn2ebuild for more details.

# NB: where a jar is provided from Portage, replace the original URI from mvn2ebuild
# with the jar path, for the first field of the appropriate line in the list below.
# See the dom4j entry for an example of this.
# Assuming the slot you have chosen is API/ABI compatible you should *not*
# change the second field, even if the actual version provided does
# not match it precisely, as Maven needs an exact coordinate match for the
# build to proceed ><

EMAVEN_VENDOR=(
	"https://repo.maven.apache.org/maven2 antlr/antlr/2.7.2/antlr-2.7.2.jar"
	"https://repo.maven.apache.org/maven2 antlr/antlr/2.7.2/antlr-2.7.2.pom"
	"https://repo.maven.apache.org/maven2 avalon-framework/avalon-framework/4.1.3/avalon-framework-4.1.3.pom"
	"https://repo.maven.apache.org/maven2 backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar"
	"https://repo.maven.apache.org/maven2 backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.pom"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1/classworlds-1.1.jar"
	"https://repo.maven.apache.org/maven2 classworlds/classworlds/1.1/classworlds-1.1.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.jar"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.jar"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/jackson-base/2.9.9/jackson-base-2.9.9.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/jackson-bom/2.9.9/jackson-bom-2.9.9.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/jackson-parent/2.9.0/jackson-parent-2.9.0.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/jackson/jackson-parent/2.9.1.2/jackson-parent-2.9.1.2.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/oss-parent/28/oss-parent-28.pom"
	"https://repo.maven.apache.org/maven2 com/fasterxml/oss-parent/34/oss-parent-34.pom"
	"https://repo.maven.apache.org/maven2 com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom"
	"https://repo.maven.apache.org/maven2 com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar"
	"https://repo.maven.apache.org/maven2 com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom"
	"https://repo.maven.apache.org/maven2 com/google/collections/google-collections/1.0/google-collections-1.0.jar"
	"https://repo.maven.apache.org/maven2 com/google/collections/google-collections/1.0/google-collections-1.0.pom"
	"https://repo.maven.apache.org/maven2 com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar"
	"https://repo.maven.apache.org/maven2 com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.pom"
	"https://repo.maven.apache.org/maven2 com/google/errorprone/error_prone_parent/2.3.2/error_prone_parent-2.3.2.pom"
	"https://repo.maven.apache.org/maven2 com/google/google/1/google-1.pom"
	"https://repo.maven.apache.org/maven2 com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar"
	"https://repo.maven.apache.org/maven2 com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.pom"
	"https://repo.maven.apache.org/maven2 com/google/guava/guava-parent/26.0-android/guava-parent-26.0-android.pom"
	"https://repo.maven.apache.org/maven2 com/google/guava/guava-parent/28.0-jre/guava-parent-28.0-jre.pom"
	"https://repo.maven.apache.org/maven2 com/google/guava/guava/28.0-jre/guava-28.0-jre.jar"
	"https://repo.maven.apache.org/maven2 com/google/guava/guava/28.0-jre/guava-28.0-jre.pom"
	"https://repo.maven.apache.org/maven2 com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"
	"https://repo.maven.apache.org/maven2 com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.pom"
	"https://repo.maven.apache.org/maven2 com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar"
	"https://repo.maven.apache.org/maven2 com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.pom"
	"https://repo.maven.apache.org/maven2 com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.jar"
	"https://repo.maven.apache.org/maven2 com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.pom"
	"https://repo.maven.apache.org/maven2 com/jcraft/jsch/0.1.54/jsch-0.1.54.jar"
	"https://repo.maven.apache.org/maven2 com/jcraft/jsch/0.1.54/jsch-0.1.54.pom"
	"https://repo.maven.apache.org/maven2 com/jcraft/jzlib/1.1.1/jzlib-1.1.1.jar"
	"https://repo.maven.apache.org/maven2 com/jcraft/jzlib/1.1.1/jzlib-1.1.1.pom"
	"https://repo.maven.apache.org/maven2 com/thoughtworks/qdox/qdox/2.0-M9/qdox-2.0-M9.jar"
	"https://repo.maven.apache.org/maven2 com/thoughtworks/qdox/qdox/2.0-M9/qdox-2.0-M9.pom"
	"https://repo.maven.apache.org/maven2 commons-beanutils/commons-beanutils/1.6/commons-beanutils-1.6.pom"
	"https://repo.maven.apache.org/maven2 commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar"
	"https://repo.maven.apache.org/maven2 commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.pom"
	"https://repo.maven.apache.org/maven2 commons-chain/commons-chain/1.1/commons-chain-1.1.jar"
	"https://repo.maven.apache.org/maven2 commons-chain/commons-chain/1.1/commons-chain-1.1.pom"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.0/commons-cli-1.0.jar"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.0/commons-cli-1.0.pom"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.2/commons-cli-1.2.jar"
	"https://repo.maven.apache.org/maven2 commons-cli/commons-cli/1.2/commons-cli-1.2.pom"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.11/commons-codec-1.11.jar"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.11/commons-codec-1.11.pom"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.3/commons-codec-1.3.pom"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.6/commons-codec-1.6.jar"
	"https://repo.maven.apache.org/maven2 commons-codec/commons-codec/1.6/commons-codec-1.6.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/2.0/commons-collections-2.0.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/2.1/commons-collections-2.1.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.1/commons-collections-3.1.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.pom"
	"https://repo.maven.apache.org/maven2 commons-collections/commons-collections/3.2/commons-collections-3.2.pom"
	"https://repo.maven.apache.org/maven2 commons-digester/commons-digester/1.6/commons-digester-1.6.pom"
	"https://repo.maven.apache.org/maven2 commons-digester/commons-digester/1.8/commons-digester-1.8.jar"
	"https://repo.maven.apache.org/maven2 commons-digester/commons-digester/1.8/commons-digester-1.8.pom"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.4/commons-io-2.4.pom"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.5/commons-io-2.5.jar"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.5/commons-io-2.5.pom"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.6/commons-io-2.6.jar"
	"https://repo.maven.apache.org/maven2 commons-io/commons-io/2.6/commons-io-2.6.pom"
	"https://repo.maven.apache.org/maven2 commons-lang/commons-lang/2.4/commons-lang-2.4.pom"
	"https://repo.maven.apache.org/maven2 commons-lang/commons-lang/2.6/commons-lang-2.6.jar"
	"https://repo.maven.apache.org/maven2 commons-lang/commons-lang/2.6/commons-lang-2.6.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.0.3/commons-logging-1.0.3.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.0/commons-logging-1.0.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.1/commons-logging-1.1.pom"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.2/commons-logging-1.2.jar"
	"https://repo.maven.apache.org/maven2 commons-logging/commons-logging/1.2/commons-logging-1.2.pom"
	"https://repo.maven.apache.org/maven2 commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar"
	"https://repo.maven.apache.org/maven2 commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.pom"
#	"https://repo.maven.apache.org/maven2 dom4j/dom4j/1.1/dom4j-1.1.jar"
	"/usr/share/dom4j-1/lib/dom4j.jar dom4j/dom4j/1.1/dom4j-1.1.jar"
	"https://repo.maven.apache.org/maven2 dom4j/dom4j/1.1/dom4j-1.1.pom"
	"https://repo.maven.apache.org/maven2 javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar"
	"https://repo.maven.apache.org/maven2 javax/annotation/jsr250-api/1.0/jsr250-api-1.0.pom"
	"https://repo.maven.apache.org/maven2 javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar"
	"https://repo.maven.apache.org/maven2 javax/enterprise/cdi-api/1.0/cdi-api-1.0.pom"
	"https://repo.maven.apache.org/maven2 javax/inject/javax.inject/1/javax.inject-1.jar"
	"https://repo.maven.apache.org/maven2 javax/inject/javax.inject/1/javax.inject-1.pom"
	"https://repo.maven.apache.org/maven2 javax/servlet/servlet-api/2.3/servlet-api-2.3.pom"
	"https://repo.maven.apache.org/maven2 joda-time/joda-time/2.10.3/joda-time-2.10.3.jar"
	"https://repo.maven.apache.org/maven2 joda-time/joda-time/2.10.3/joda-time-2.10.3.pom"
	"https://repo.maven.apache.org/maven2 junit/junit/3.8.1/junit-3.8.1.jar"
	"https://repo.maven.apache.org/maven2 junit/junit/3.8.1/junit-3.8.1.pom"
	"https://repo.maven.apache.org/maven2 junit/junit/4.12/junit-4.12.jar"
	"https://repo.maven.apache.org/maven2 junit/junit/4.12/junit-4.12.pom"
	"https://repo.maven.apache.org/maven2 kr/motd/maven/os-maven-plugin/1.6.1/os-maven-plugin-1.6.1.jar"
	"https://repo.maven.apache.org/maven2 kr/motd/maven/os-maven-plugin/1.6.1/os-maven-plugin-1.6.1.pom"
	"https://repo.maven.apache.org/maven2 log4j/log4j/1.2.12/log4j-1.2.12.pom"
	"https://repo.maven.apache.org/maven2 logkit/logkit/1.0.1/logkit-1.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/10/apache-10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/11/apache-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/13/apache-13.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/15/apache-15.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/16/apache-16.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/17/apache-17.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/18/apache-18.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/19/apache-19.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/2/apache-2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/21/apache-21.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/23/apache-23.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/3/apache-3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/4/apache-4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/5/apache-5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/6/apache-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/7/apache-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/apache/9/apache-9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-compress/1.19/commons-compress-1.19.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-compress/1.20/commons-compress-1.20.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/11/commons-parent-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/17/commons-parent-17.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/22/commons-parent-22.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/25/commons-parent-25.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/34/commons-parent-34.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/35/commons-parent-35.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/39/commons-parent-39.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/41/commons-parent-41.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/42/commons-parent-42.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/47/commons-parent-47.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/48/commons-parent-48.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/5/commons-parent-5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/commons/commons-parent/9/commons-parent-9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/geronimo/genesis/genesis-default-flava/2.0/genesis-default-flava-2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/geronimo/genesis/genesis-java5-flava/2.0/genesis-java5-flava-2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/geronimo/genesis/genesis/2.0/genesis-2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpclient/4.0.2/httpclient-4.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpclient/4.5.8/httpclient-4.5.8.jar"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpclient/4.5.8/httpclient-4.5.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-client/4.0.2/httpcomponents-client-4.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-client/4.5.8/httpcomponents-client-4.5.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-core/4.0.1/httpcomponents-core-4.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-core/4.4.11/httpcomponents-core-4.4.11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcomponents-parent/11/httpcomponents-parent-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.jar"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/project/4.0/project-4.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/httpcomponents/project/4.1/project-4.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-core/1.9/doxia-core-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-core/1.9/doxia-core-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-decoration-model/1.7.4/doxia-decoration-model-1.7.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-decoration-model/1.7.4/doxia-decoration-model-1.7.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-decoration-model/1.9/doxia-decoration-model-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.9/doxia-logging-api-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-logging-api/1.9/doxia-logging-api-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml/1.9/doxia-module-xhtml-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml/1.9/doxia-module-xhtml-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml5/1.9/doxia-module-xhtml5-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-module-xhtml5/1.9/doxia-module-xhtml5-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-modules/1.7/doxia-modules-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-modules/1.9/doxia-modules-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.9/doxia-sink-api-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sink-api/1.9/doxia-sink-api-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-site-renderer/1.7.4/doxia-site-renderer-1.7.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-site-renderer/1.9/doxia-site-renderer-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-site-renderer/1.9/doxia-site-renderer-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sitetools/1.7.4/doxia-sitetools-1.7.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-sitetools/1.9/doxia-sitetools-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-skin-model/1.7.4/doxia-skin-model-1.7.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-skin-model/1.9/doxia-skin-model-1.9.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia-skin-model/1.9/doxia-skin-model-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.7/doxia-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/doxia/doxia/1.9/doxia-1.9.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-aether-provider/3.0/maven-aether-provider-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-archiver/3.5.0/maven-archiver-3.5.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-archiver/3.5.0/maven-archiver-3.5.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact-manager/2.2.1/maven-artifact-manager-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.5/maven-artifact-2.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/2.2.1/maven-artifact-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-compat/3.0/maven-compat-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-compat/3.0/maven-compat-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/3.0/maven-core-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-core/3.0/maven-core-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-error-diagnostics/2.2.1/maven-error-diagnostics-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model-builder/3.0/maven-model-builder-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model-builder/3.0/maven-model-builder-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/3.0/maven-model-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/3.0/maven-model-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/3.5.3/maven-model-3.5.3.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-model/3.5.3/maven-model-3.5.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-monitor/2.2.1/maven-monitor-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/10/maven-parent-10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/11/maven-parent-11.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/15/maven-parent-15.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/16/maven-parent-16.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/21/maven-parent-21.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/22/maven-parent-22.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/23/maven-parent-23.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/25/maven-parent-25.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/26/maven-parent-26.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/27/maven-parent-27.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/30/maven-parent-30.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/31/maven-parent-31.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/33/maven-parent-33.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/34/maven-parent-34.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-parent/5/maven-parent-5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.0.6/maven-plugin-api-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/2.2.1/maven-plugin-api-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/3.0/maven-plugin-api-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/3.0/maven-plugin-api-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/3.5.3/maven-plugin-api-3.5.3.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-api/3.5.3/maven-plugin-api-3.5.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-descriptor/2.2.1/maven-plugin-descriptor-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-parameter-documenter/2.2.1/maven-plugin-parameter-documenter-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-plugin-registry/2.2.1/maven-plugin-registry-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-profile/2.2.1/maven-profile-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-project/2.2.1/maven-project-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/2.2.1/maven-repository-metadata-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-repository-metadata/3.0/maven-repository-metadata-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings-builder/3.0/maven-settings-builder-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings-builder/3.0/maven-settings-builder-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/2.2.1/maven-settings-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/3.0/maven-settings-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-settings/3.0/maven-settings-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/2.2.1/maven-toolchain-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/3.0-alpha-2/maven-toolchain-3.0-alpha-2.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven-toolchain/3.0-alpha-2/maven-toolchain-3.0-alpha-2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.5/maven-2.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.0.6/maven-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/2.2.1/maven-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/3.0-alpha-2/maven-3.0-alpha-2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/3.0/maven-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/maven/3.5.3/maven-3.5.3.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-assembly-plugin/3.2.0/maven-assembly-plugin-3.2.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-assembly-plugin/3.2.0/maven-assembly-plugin-3.2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-clean-plugin/3.1.0/maven-clean-plugin-3.1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-clean-plugin/3.1.0/maven-clean-plugin-3.1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-compiler-plugin/3.8.1/maven-compiler-plugin-3.8.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-dependency-plugin/3.1.2/maven-dependency-plugin-3.1.2.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-dependency-plugin/3.1.2/maven-dependency-plugin-3.1.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-jar-plugin/3.2.0/maven-jar-plugin-3.2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/31/maven-plugins-31.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/33/maven-plugins-33.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-plugins/34/maven-plugins-34.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M4/maven-surefire-plugin-3.0.0-M4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M4/maven-surefire-plugin-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting-impl/3.0.0/maven-reporting-impl-3.0.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting/2.0.6/maven-reporting-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/reporting/maven-reporting/2.2.1/maven-reporting-2.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/file-management/3.0.0/file-management-3.0.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/file-management/3.0.0/file-management-3.0.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-artifact-transfer/0.11.0/maven-artifact-transfer-0.11.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-artifact-transfer/0.11.0/maven-artifact-transfer-0.11.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/3.1.0/maven-common-artifact-filters-3.1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-common-artifact-filters/3.1.0/maven-common-artifact-filters-3.1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-dependency-analyzer/1.11.1/maven-dependency-analyzer-1.11.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-dependency-analyzer/1.11.1/maven-dependency-analyzer-1.11.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/1.1/maven-filtering-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-filtering/3.1.1/maven-filtering-3.1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/17/maven-shared-components-17.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/18/maven-shared-components-18.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/19/maven-shared-components-19.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/21/maven-shared-components-21.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/22/maven-shared-components-22.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/30/maven-shared-components-30.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-components/33/maven-shared-components-33.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-incremental/1.1/maven-shared-incremental-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-io/3.0.0/maven-shared-io-3.0.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/3.1.0/maven-shared-utils-3.1.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/maven-surefire-common/3.0.0-M4/maven-surefire-common-3.0.0-M4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/maven-surefire-common/3.0.0-M4/maven-surefire-common-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-api/3.0.0-M4/surefire-api-3.0.0-M4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-api/3.0.0-M4/surefire-api-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-booter/3.0.0-M4/surefire-booter-3.0.0-M4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-booter/3.0.0-M4/surefire-booter-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-extensions-api/3.0.0-M4/surefire-extensions-api-3.0.0-M4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-extensions-api/3.0.0-M4/surefire-extensions-api-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-logger-api/3.0.0-M4/surefire-logger-api-3.0.0-M4.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire-logger-api/3.0.0-M4/surefire-logger-api-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/surefire/surefire/3.0.0-M4/surefire-3.0.0-M4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/1.0-beta-6/wagon-provider-api-1.0-beta-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-2.10.jar"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon-provider-api/2.10/wagon-provider-api-2.10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon/1.0-beta-6/wagon-1.0-beta-6.pom"
	"https://repo.maven.apache.org/maven2 org/apache/maven/wagon/wagon/2.10/wagon-2.10.pom"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-master/4/struts-master-4.pom"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-parent/1.3.8/struts-parent-1.3.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar"
	"https://repo.maven.apache.org/maven2 org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.pom"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity/1.6.2/velocity-1.6.2.pom"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity/1.7/velocity-1.7.jar"
	"https://repo.maven.apache.org/maven2 org/apache/velocity/velocity/1.7/velocity-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.jar"
	"https://repo.maven.apache.org/maven2 org/apache/xbean/xbean-reflect/3.7/xbean-reflect-3.7.pom"
	"https://repo.maven.apache.org/maven2 org/apache/xbean/xbean/3.7/xbean-3.7.pom"
	"https://repo.maven.apache.org/maven2 org/checkerframework/checker-qual/2.8.1/checker-qual-2.8.1.jar"
	"https://repo.maven.apache.org/maven2 org/checkerframework/checker-qual/2.8.1/checker-qual-2.8.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/mojo/animal-sniffer-parent/1.17/animal-sniffer-parent-1.17.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/4.2.0/plexus-archiver-4.2.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/4.2.1/plexus-archiver-4.2.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/4.2.1/plexus-archiver-4.2.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/4.2.2/plexus-archiver-4.2.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-archiver/4.2.2/plexus-archiver-4.2.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.5.1/plexus-classworlds-2.5.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.5.2/plexus-classworlds-2.5.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-classworlds/2.5.2/plexus-classworlds-2.5.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-api/2.8.4/plexus-compiler-api-2.8.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-javac/2.8.4/plexus-compiler-javac-2.8.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler-manager/2.8.4/plexus-compiler-manager-2.8.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compiler/2.8.4/plexus-compiler-2.8.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-compilers/2.8.4/plexus-compilers-2.8.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.5.4/plexus-component-annotations-1.5.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/1.7.1/plexus-component-annotations-1.7.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/2.0.0/plexus-component-annotations-2.0.0.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-component-annotations/2.0.0/plexus-component-annotations-2.0.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.12/plexus-components-1.1.12.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.18/plexus-components-1.1.18.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-components/4.0/plexus-components-4.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.7.1/plexus-container-default-1.7.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-container-default/1.7.1/plexus-container-default-1.7.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.0-alpha-30/plexus-containers-1.0-alpha-30.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.5.4/plexus-containers-1.5.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.5.5/plexus-containers-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/1.7.1/plexus-containers-1.7.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-containers/2.0.0/plexus-containers-2.0.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-i18n/1.0-beta-10/plexus-i18n-1.0-beta-10.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-i18n/1.0-beta-10/plexus-i18n-1.0-beta-10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.22/plexus-interpolation-1.22.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/3.2.0/plexus-io-3.2.0.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-io/3.2.0/plexus-io-3.2.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-java/0.9.10/plexus-java-0.9.10.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-java/0.9.10/plexus-java-0.9.10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-java/1.0.3/plexus-java-1.0.3.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-java/1.0.3/plexus-java-1.0.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-languages/0.9.10/plexus-languages-0.9.10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-languages/1.0.3/plexus-languages-1.0.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.2/plexus-utils-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.4.5/plexus-utils-1.4.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.24/plexus-utils-3.0.24.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.1.0/plexus-utils-3.1.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-velocity/1.2/plexus-velocity-1.2.jar"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus-velocity/1.2/plexus-velocity-1.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.10/plexus-1.0.10.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.5/plexus-2.0.5.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.1/plexus-3.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/3.3.1/plexus-3.3.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/4.0/plexus-4.0.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/5.1/plexus-5.1.pom"
	"https://repo.maven.apache.org/maven2 org/codehaus/plexus/plexus/6.1/plexus-6.1.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar"
	"https://repo.maven.apache.org/maven2 org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/aether/aether/0.9.0.M2/aether-0.9.0.M2.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/jgit/org.eclipse.jgit-parent/5.2.2.201904231744-r/org.eclipse.jgit-parent-5.2.2.201904231744-r.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/jgit/org.eclipse.jgit/5.2.2.201904231744-r/org.eclipse.jgit-5.2.2.201904231744-r.jar"
	"https://repo.maven.apache.org/maven2 org/eclipse/jgit/org.eclipse.jgit/5.2.2.201904231744-r/org.eclipse.jgit-5.2.2.201904231744-r.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar"
	"https://repo.maven.apache.org/maven2 org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.3/org.eclipse.sisu.plexus-0.3.3.jar"
	"https://repo.maven.apache.org/maven2 org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.3/org.eclipse.sisu.plexus-0.3.3.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/sisu/sisu-inject/0.3.3/sisu-inject-0.3.3.pom"
	"https://repo.maven.apache.org/maven2 org/eclipse/sisu/sisu-plexus/0.3.3/sisu-plexus-0.3.3.pom"
	"https://repo.maven.apache.org/maven2 org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"
	"https://repo.maven.apache.org/maven2 org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/iq80/snappy/snappy/0.4/snappy-0.4.jar"
	"https://repo.maven.apache.org/maven2 org/iq80/snappy/snappy/0.4/snappy-0.4.pom"
	"https://repo.maven.apache.org/maven2 org/jboss/weld/weld-api-bom/1.0/weld-api-bom-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/jboss/weld/weld-api-parent/1.0/weld-api-parent-1.0.pom"
	"https://repo.maven.apache.org/maven2 org/jboss/weld/weld-parent/6/weld-parent-6.pom"
	"https://repo.maven.apache.org/maven2 org/ow2/asm/asm/6.2/asm-6.2.jar"
	"https://repo.maven.apache.org/maven2 org/ow2/asm/asm/6.2/asm-6.2.pom"
	"https://repo.maven.apache.org/maven2 org/ow2/asm/asm/7.0/asm-7.0.jar"
	"https://repo.maven.apache.org/maven2 org/ow2/asm/asm/7.0/asm-7.0.pom"
	"https://repo.maven.apache.org/maven2 org/ow2/asm/asm/7.3.1/asm-7.3.1.jar"
	"https://repo.maven.apache.org/maven2 org/ow2/asm/asm/7.3.1/asm-7.3.1.pom"
	"https://repo.maven.apache.org/maven2 org/ow2/ow2/1.5/ow2-1.5.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/jcl-over-slf4j/1.5.6/jcl-over-slf4j-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-parent/1.5.6/slf4j-parent-1.5.6.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-parent/1.7.2/slf4j-parent-1.7.2.pom"
	"https://repo.maven.apache.org/maven2 org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-api/1.7/aether-api-1.7.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-api/1.7/aether-api-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-impl/1.7/aether-impl-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-parent/1.7/aether-parent-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-spi/1.7/aether-spi-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/aether/aether-util/1.7/aether-util-1.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/10/forge-parent-10.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/3/forge-parent-3.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/4/forge-parent-4.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/5/forge-parent-5.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/forge/forge-parent/6/forge-parent-6.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/oss/oss-parent/5/oss-parent-5.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/oss/oss-parent/6/oss-parent-6.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/oss/oss-parent/7/oss-parent-7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/oss/oss-parent/9/oss-parent-9.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/inject/guice-bean/1.4.2/guice-bean-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/inject/guice-plexus/1.4.2/guice-plexus-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-inject/1.4.2/sisu-inject-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/sisu/sisu-parent/1.4.2/sisu-parent-1.4.2.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/10/spice-parent-10.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/12/spice-parent-12.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/15/spice-parent-15.pom"
	"https://repo.maven.apache.org/maven2 org/sonatype/spice/spice-parent/17/spice-parent-17.pom"
	"https://repo.maven.apache.org/maven2 org/tukaani/xz/1.8/xz-1.8.jar"
	"https://repo.maven.apache.org/maven2 org/tukaani/xz/1.8/xz-1.8.pom"
	"https://repo.maven.apache.org/maven2 oro/oro/2.0.8/oro-2.0.8.jar"
	"https://repo.maven.apache.org/maven2 oro/oro/2.0.8/oro-2.0.8.pom"
	"https://repo.maven.apache.org/maven2 pl/project13/maven/git-commit-id-plugin/3.0.1/git-commit-id-plugin-3.0.1.jar"
	"https://repo.maven.apache.org/maven2 pl/project13/maven/git-commit-id-plugin/3.0.1/git-commit-id-plugin-3.0.1.pom"
	"https://repo.maven.apache.org/maven2 sslext/sslext/1.2-0/sslext-1.2-0.jar"
	"https://repo.maven.apache.org/maven2 sslext/sslext/1.2-0/sslext-1.2-0.pom"
	"https://repo.maven.apache.org/maven2 xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom"
	"https://repo.maven.apache.org/maven2 xmlunit/xmlunit/1.5/xmlunit-1.5.pom"
)

java-maven-pkg_setup_maven_src_uri

EMAVEN_PARAMS+=" -Pbuild-usrsctp -Pbuild-jnisctp"
EMAVEN_INSTALL_JAR_FROM="jniwrapper/native/target/jniwrapper-native-1.0-SNAPSHOT-linux-<ARCH>.jar"
EMAVEN_INSTALL_JAR_TO="${PN}-native-<ARCH>.jar"

src_install() {
	java-maven-pkg_src_install
	# as well as the native target, we'll also need the
	# matching jnilib (when e.g. patching an otherwise unsupported
	# arch into a jitsi-videobridge install tree); so, add it
	java-pkg_dojar jniwrapper/jnilib/target/jnilib-1.0-SNAPSHOT.jar
}




